#!/bin/sh -ex
if false
then
        sudo $HOME/tmp/diskdev_cmds-332.11/fsck_hfs.tproj/fsck_hfs /dev/sda3
        pmount -w /dev/sda3
        sudo chown -R bam:microcom /media/sda3/cgc
        pumount /dev/sda3
fi

#pmount -r /dev/sda3
sudo chown -R bam:microcom /media/'Brian May'/cgc
rsync -avP --update /media/'Brian May'/cgc $HOME
#pumount /dev/sda3
