#!/bin/sh -e
# Update vacation status for user.
# Note: will destroy any existing .forward and/or .vacation.msg files.

TEMP=`getopt -o '' --long enable,disable -n'update_vacation' -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMP"

OPERATION=""

while true
do
	case "$1" in
	--enable)
		OPERATION="enable"
		shift
		;;
	--disable)
		OPERATION="disable"
		shift
		;;
	--)
		shift
		break
		;;
	*) echo "Internal error!" ; exit 1 ;;
	esac
done

usage() {
	echo "Usage: update_vacation --enable userid < message" 2>&1
	echo "Usage: update_vacation --disable userid" 2>&1
	exit 1
}

if [ -z $1 ]
then
	echo "User not given" 2>&1
	usage
fi

ID="$1"
shift

if [ ! -f /etc/mailname ]
then
        echo "/etc/mailname not configured" 2>&1
        exit 1;
fi
mailname=`cat /etc/mailname`

IDLINE=`getent passwd $ID` || ( echo "Unknown User $ID" 2>&1; exit 255 )
DIR=`echo $IDLINE | gawk -F: '{ print $6; }'`
NAME=`echo $IDLINE | gawk -F: '{ print $5; }' | gawk -F, '{ print $1; }'`

case "$OPERATION" in
enable)
        cat << EOF > $DIR/.vacation.msg.new
From: $NAME <$ID@$mailname>
Subject: Out of the office
Delivered-By-The-Graces-Of: The Vacation program
Precedence: bulk

EOF
        sed "s/NAME/$NAME/g; s/ID/$ID/g" >> $DIR/.vacation.msg.new
	echo "$ID, \"|/usr/bin/vacation $ID\"" > $DIR/.forward.new
	chown $ID $DIR/.vacation.msg.new $DIR/.forward.new
	chmod 644 $DIR/.vacation.msg.new $DIR/.forward.new
	mv $DIR/.vacation.msg.new $DIR/.vacation.msg
	rm -f $DIR/.vacation.db
	mv $DIR/.forward.new $DIR/.forward
	;;
disable)
	rm -f $DIR/.forward
	rm -f $DIR/.vacation.db
	;;
*)
	echo "Internal error parameters" 2>&1
	usage
	;;
esac
