#!/bin/sh
set -ex

if [ -z "$1" ]
then
    echo "No distro name given" 1>&2
    exit 1
fi
DIST="$1"
shift

if [ -z "$1" ]
then
    echo "No suite name given" 1>&2
    exit 1
fi
SUITE="$1"
shift

VG="aquitard"
LV="schroot-$SUITE"
ARCH=""

if [ "$1" = "i386" ]
then
    LV="$LV-i386"
    ARCH="--arch=i386"
fi

lvcreate -L2G -n "$LV" "$VG"
mkfs.ext4 "/dev/$VG/$LV"
mount "/dev/$VG/$LV" /mnt
debootstrap $ARCH "$SUITE" /mnt "http://hq.in.vpac.org:9999/$DIST"
#debootstrap --keyring="$PWD/debian.gpg" "$SUITE" /mnt http://hq.in.vpac.org:9999/debian
echo 'APT::Install-Recommends "false";' > /mnt/etc/apt/apt.conf
chmod 644 /mnt/etc/apt/apt.conf
chroot /mnt apt-get update
chroot /mnt apt-get upgrade
chroot /mnt apt-get --yes install locales
chroot /mnt apt-get --yes install build-essential devscripts fakeroot zsh
umount /mnt
