#!/bin/sh -ex

TEMP=`getopt -o '' --long chroot:,rsign: -n'sbuild_cwd' -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMP"

CHROOT="auto"

while true
do
	case "$1" in
	--chroot)
		shift
		CHROOT="$1"
		shift;
		;;
	--rsign)
		shift
		RSIGN="$1"
		shift;
		;;
	--)
		shift;
		break ;;
	*) echo "Internal error!" ; exit 1 ;;
	esac
done

ARCH="`dpkg-architecture | sed -n 's/^DEB_BUILD_ARCH=//p'`"
SOURCE="`dpkg-parsechangelog|sed -n 's/^Source: //p'`"
VERSION="`dpkg-parsechangelog|sed -n 's/^Version: \(.*:\|\)//p'`"
DISTRIBUTION="`dpkg-parsechangelog|sed -n 's/^Distribution: \(.*:\|\)//p'`"
DSC="$SOURCE"_"$VERSION".dsc
CHANGES="$SOURCE"_"$VERSION"_"$ARCH".changes

if [ "$CHROOT" = "auto" ]
then
    CHROOT="$DISTRIBUTION"
fi

session=`schroot -b -c "$CHROOT"`
trap "schroot -e -c '$session'" 0 TERM INT QUIT
schroot -r -c "$session" -u root -- apt-get --yes install devscripts lintian debhelper cdbs quilt
schroot -r -c "$session" -- debuild -us -uc -S

cd ..

SRC_DIR="$PWD"
BUILD_DIR="build/$DISTRIBUTION"
if [ ! -d "$BUILD_DIR" ]
then
    mkdir -p "$BUILD_DIR"
fi
cd "$BUILD_DIR"

sbuild -As --chroot="$CHROOT" --dist="$DISTRIBUTION" "$SRC_DIR/$DSC"

schroot -r -c "$session" -- lintian "$CHANGES" || true
trap "" 0 TERM INT QUIT
schroot -e -c "$session"

if [ -z "$RSIGN" ]
then
    debsign "$CHANGES"
else
    debrsign "$RSIGN" "$CHANGES"
fi
