#!/bin/sh -ex

TEMP=`getopt -o '' --long distribution: -n'sbuild_cwd' -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMP"

DISTRIBUTION="lenny"

while true
do
	case "$1" in
	--distribution)
		shift
		DISTRIBUTION="$1"
		shift;
		;;
	--)
		shift;
		break ;;
	*) echo "Internal error!" ; exit 1 ;;
	esac
done

ARCH="`dpkg-architecture | sed -n 's/^DEB_BUILD_ARCH=//p'`"
SOURCE="`dpkg-parsechangelog|sed -n 's/^Source: //p'`"
VERSION="`dpkg-parsechangelog|sed -n 's/^Version: \(.*:\|\)//p'`"
DSC="$SOURCE"_"$VERSION".dsc
CHANGES="$SOURCE"_"$VERSION"_"$ARCH".changes

debuild -us -uc -S
cd ..
sbuild -As --dist="$DISTRIBUTION" $DSC
debsign "$CHANGES"
