#!/bin/sh
set -e

for i in `schroot -l`; do
    case "$i" in
    centos*-source)
        echo ""
        echo "$i -- yum"
        echo "-------------------------------------------"
        schroot -c "$i" -- yum update
        echo "-------------------------------------------"
        ;;
    *-source)
        echo ""
        echo "$i -- apt-get"
        echo "-------------------------------------------"
        schroot -c "$i" -- apt-get update
        schroot -c "$i" -- apt-get --yes dist-upgrade
        schroot -c "$i" -- apt-get autoremove --purge
        schroot -c "$i" -- apt-get clean
        echo "-------------------------------------------"
        ;;
    esac
done
