#!/bin/sh -e

TEMP=`getopt -o '' --long sa,type:,chroot:,chroot-force,key:,username: -n'sbuild_cwd' -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMP"

OPTS=""
USERNAME=""
KEY=""
CHROOT=""
TYPE="full"
CHROOT=""
CHROOT_FORCE=""

while true
do
	case "$1" in
	--sa)
		shift
		OPTS="$OPTS -sa"
		;;
	--key)
		shift
		KEY="$1"
		shift;
		;;
	--username)
		shift
		USERNAME="$1"
		shift;
		;;
	--type)
		shift
		TYPE="$1"
		shift
		;;
	--chroot)
		shift
		CHROOT="$1"
		shift;
		;;
	--chroot-force)
		CHROOT_FORCE="yes"
		shift
		;;
	--)
		shift;
		break ;;
	*) echo "Internal error!" ; exit 1 ;;
	esac
done

if [ "$TYPE" != "full" ] && [ "$TYPE" != "source" ] && [ "$TYPE" != "binary" ]
then
    echo "Unknown type of $TYPE" >&2
    exit 1
fi

git config gitpkg.admin-config-hook "$HOME/tree/junk/debian/schroot/gitpkg-hooks/admin-config-hook"
git config gitpkg.deb-export-hook  "$HOME/tree/debian/gitpkg/hooks/debcherry-deb-export-hook"
git config gitpkg.exit-hook "$HOME/tree/junk/debian/schroot/gitpkg-hooks/exit-hook"
git config gitpkg.force-overwrite-orig never

(
    export PATH=/home/brian/tree/debian/gitpkg:$PATH
    export DEB_BUILD_OPTS="$OPTS"
    export DEB_BUILD_CHROOT="$CHROOT"
    export DEB_BUILD_CHROOT_FORCE="$CHROOT_FORCE"
    export DEB_BUILD_KEY="$KEY"
    export DEB_BUILD_USERNAME="$USERNAME"
    export DEB_BUILD_TYPE="$TYPE"
    gitpkg "$@"
)
