#!/bin/sh
set -ex

if [ -z "$1" ]
then
    echo "No distro name given" 1>&2
    exit 1
fi
DIST="$1"
shift

if [ -z "$1" ]
then
    echo "No suite name given" 1>&2
    exit 1
fi
SUITE="$1"
shift

if [ "$1" = "amd64" ]
then
    NAME="$SUITE"
    ARCH="--arch=amd64"
elif [ "$1" = "i386" ]
then
    NAME="$SUITE-i386"
    ARCH="--arch=i386"
else
    echo "Unknown cpu type $1" 1>&2
    exit 1
fi

case "$(hostname --short)" in
aquitard)
	VG="aquitard"
	LV="schroot-$NAME"

	DIR="/mnt"
	UMOUNT="yes"
	MIRROR="http://hq.in.vpac.org:9999/$DIST"

	lvcreate -L2G -n "$LV" "$VG"
	mkfs.ext4 "/dev/$VG/$LV"
	mount "/dev/$VG/$LV" "$DIR"
	;;

merlock)
	DIR="/srv/chroot/$NAME"
	UMOUNT=""
	MIRROR="http://proxy.pri:9999/$DIST"
	;;

*)
	DIR="/srv/chroot/$NAME"
	UMOUNT=""
	MIRROR="http://ftp.au.debian.org/$DIST"
	;;
esac

debootstrap "$ARCH" "$SUITE" "$DIR" "$MIRROR"
echo 'APT::Install-Recommends "false";' > "$DIR"/etc/apt/apt.conf
chmod 644 "$DIR"/etc/apt/apt.conf
chroot "$DIR" apt-get update
chroot "$DIR" apt-get upgrade
chroot "$DIR" apt-get --yes install locales
chroot "$DIR" apt-get --yes install build-essential devscripts fakeroot zsh

if [ -n "$UMOUNT" ]
then
	umount "$DIR"
fi
