#!/bin/sh -ex

TEMP=`getopt -o '' --long sa,arch:,username:,internal -n'upload_ppa' -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMP"

OPTS=""
ARCH=""
SA=""
DEST="vpac"

while true
do
	case "$1" in
	--sa)
		shift
		SA = "--sa"
		;;
	--username)
		shift
		OPTS="$OPTS --username $1"
		shift;
		;;
	--arch)
		shift
		ARCH="$ARCH $1"
		shift;
		;;
	--internal)
		DEST="internal"
		shift;
		;;
	--)
		shift;
		break ;;
	*) echo "Internal error!" ; exit 1 ;;
	esac
done

if [ -z "$ARCH" ]
then
    ARCH="amd64"
fi

NAME="`dpkg-parsechangelog|sed -n 's/^Source: \(.*:\|\)//p'`"
VERSION="`dpkg-parsechangelog|sed -n 's/^Version: \(.*:\|\)//p'`"
UPSTREAM="`echo "$VERSION" | sed 's/-[\.0-9]\+$//'`"

cd ..
SRCDIR="$PWD"

TMPDIR=$(mktemp -d)
trap "rm -rf -- '$TMPDIR'" EXIT HUP INT TERM

cp "$SRCDIR/$NAME""_$UPSTREAM".orig.tar.gz "$TMPDIR"

cd "$TMPDIR"
for chroot in "$@"
do
    dpkg-source -x "$SRCDIR/$NAME""_$VERSION".dsc

    cd "$NAME""-$UPSTREAM"
    if [ "$chroot" = "squeeze" ]
    then
        THIS_VERSION="$VERSION~bpo60+1"
        dch -b -v "$THIS_VERSION" --force-distribution --distribution $chroot "Rebuild for $chroot."
    else
        THIS_VERSION="$VERSION"
        dch -a --force-distribution --distribution $chroot ""
    fi

    first="yes"
    for arch in "$ARCH"
    do
        if [ "$arch" = "amd64" ]
        then
            arch_chroot="$chroot"
        else
            arch_chroot="$chroot-$arch"
        fi

        if [ -n "$first" ]
        then
            ~/tree/junk/debian/schroot/sbuild_cwd --mode raw --chroot "$arch_chroot" --build "all" $OPTS $SA
            first=""
        else
            ~/tree/junk/debian/schroot/sbuild_cwd --mode raw --chroot "$arch_chroot" --build "arch-dependent" $OPTS
        fi
        dput "$DEST" ../"$NAME""_$THIS_VERSION""_$arch.changes"
    done

    SA="--sd"
    cd ..
    rm -rf "$NAME""-$UPSTREAM"
done
