#!/bin/sh -ex

TEMP=`getopt -o '' --long sa,username: -n'upload_ppa' -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMP"

OPTS=""
USERNAME=""

while true
do
	case "$1" in
	--sa)
		shift
		OPTS="$OPTS -sa"
		;;
	--username)
		shift
		USERNAME="$1"
		shift;
		;;
	--)
		shift;
		break ;;
	*) echo "Internal error!" ; exit 1 ;;
	esac
done


NAME="`dpkg-parsechangelog|sed -n 's/^Source: \(.*:\|\)//p'`"
VERSION="`dpkg-parsechangelog|sed -n 's/^Version: \(.*:\|\)//p'`"
UPSTREAM="`echo "$VERSION" | sed 's/-[0-9]\+$//'`"

cd ..
SRCDIR="$PWD"

TMPDIR=$(mktemp -d)
trap "rm -rf -- '$TMPDIR'" EXIT HUP INT TERM
cd "$TMPDIR"

dpkg-source -x "$SRCDIR/$NAME""_$VERSION".dsc
cp "$SRCDIR/$NAME""_$UPSTREAM".orig.tar.gz .

cd "$NAME""-$UPSTREAM"
debuild -i -S -uc -us $OPTS
cd ..

if [ -z "$USERNAME" ]
then
    debsign "$NAME""_$VERSION""_source.changes"
else
    debrsign "$USERNAME" "$NAME""_$VERSION""_source.changes"
fi
~/tree/junk/debian/schroot/chroot_dput ppa-precise:brian-microcomaustralia/django "$NAME""_$VERSION""_source.changes"
