#!/bin/sh
set -ex

session="squeeze-i386-71bd0f84-ab26-45e2-b53e-585f65cfcd61"
distro=squeeze

if [ -z "$session" ]
then
    session=`schroot -b -c $distro-i386`
fi
schroot -r -c "$session" -u root -- apt-get --yes install debhelper automake autoconf libtool unixodbc-dev libasound2-dev libcurl3-openssl-dev libssl-dev ncurses-dev libogg-dev libvorbis-dev libperl-dev libgdbm-dev libdb-dev libgnutls-dev libtiff4-dev python libx11-dev uuid-dev python-dev git-core erlang-dev doxygen libexpat1-dev bison ladspa-sdk libpq-dev libsnmp-dev default-jdk gcj-jdk libyaml-dev
#trap "schroot -e -c '$session'" 0 TERM INT QUIT

if false
then
    ver="$(cat build/next-release.txt | sed -e 's/-/~/g')~n$(date +%Y%m%dT%H%M%SZ)-1~${distro}+1"
    git clean -fdx && git reset --hard HEAD
    cp ../modules.conf .
    ./build/set-fs-version.sh "$ver"

    cd debian && schroot -r -c "$session" -- ./bootstrap.sh -c "$distro" && cd ..
    schroot -r -c "$session" -- dpkg-checkbuilddeps
    schroot -r -c "$session" -- ./bootstrap.sh
    schroot -r -c "$session" -- ./configure --prefix=/opt/freeswitch --enable-core-libedit-support --enable-core-odbc-support --with-libcurl --with-openssl
fi
schroot -r -c "$session" -- make

#  distro=sid
#  ver="$(cat build/next-release.txt | sed -e 's/-/~/g')~n$(date +%Y%m%dT%H%M%SZ)-1~${distro}+1"
#  git clean -fdx && git reset --hard HEAD
#  ./build/set-fs-version.sh "$ver"
#  git add configure.in && git commit -m "bump to custom v$ver"
#  (cd debian && ./bootstrap.sh -c $distro)
#  dch -b -m -v "$ver" --force-distribution -D "$suite" "Custom build."
#  git-buildpackage -b -us -uc \
#    --git-verbose \
#    --git-pbuilder --git-dist=$distro \
#    --git-compression-level=1v --git-compression=xz
#  git reset --hard HEAD^


umask 022
schroot -r -c "$session" -u root -- rm -rf "$PWD/debian/tmp"
schroot -r -c "$session" -u root -- make DESTDIR="$PWD/debian/tmp" install
schroot -r -c "$session" -- make DESTDIR="$PWD/debian/tmp" samples-conf
ln -s ../freeswitch-sounds/* .
for i in cd-sounds-install cd-moh-install uhd-sounds-install uhd-moh-install hd-sounds-install hd-moh-install sounds-install moh-install
do
    schroot -r -c "$session" -u root -- make DESTDIR="$PWD/debian/tmp" "$i"
done

#schroot -e -c "$session"
#trap "" 0 TERM INT QUIT
