#!/bin/sh
set -ex

#session="lenny-i386-1dcedac3-4ab2-4b6c-ae25-06141b4a4ac5"
if [ -z "$session" ]
then
    session=`schroot -b -c lenny-i386`
fi
#trap "echo 'clean up: schroot -e -c $session'" 0 TERM INT QUIT
trap "schroot -e -c '$session'" 0 TERM INT QUIT
schroot -r -c "$session" -u root -- apt-get --yes install debhelper automake autoconf libtool unixodbc-dev libasound2-dev libcurl3-openssl-dev libssl-dev ncurses-dev libogg-dev libvorbis-dev libperl-dev libgdbm-dev libdb-dev libgnutls-dev libtiff4-dev python libx11-dev uuid-dev python-dev git-core
schroot -r -c "$session" -- dpkg-checkbuilddeps
#schroot -r -c "$session" -u root -- debian/rules clean
#schroot -r -c "$session" -- ./bootstrap.sh
#schroot -r -c "$session" -- ./configure --prefix=/opt/freeswitch --enable-core-libedit-support --enable-core-odbc-support --with-libcurl --with-openssl
schroot -r -c "$session" -- make

umask 022
schroot -r -c "$session" -u root -- rm -rf "$PWD/debian/tmp"
schroot -r -c "$session" -u root -- make DESTDIR="$PWD/debian/tmp" install
schroot -r -c "$session" -- make DESTDIR="$PWD/debian/tmp" samples-conf
for i in cd-sounds-install cd-moh-install uhd-sounds-install uhd-moh-install hd-sounds-install hd-moh-install sounds-install moh-install
do
    schroot -r -c "$session" -u root -- make DESTDIR="$PWD/debian/tmp" "$i"
done

#schroot -r -c "$session" -- debian/rules build
#schroot -r -c "$session" -- fakeroot debian/rules binary
schroot -e -c "$session"
trap "" 0 TERM INT QUIT
